"""Botanical art direction for the 70 flower additions, researched 2026-10-08.

Height and bloom_radius are metres; days is compressed game time. Wildlife is
a game attraction tag, not a complete scientific pollinator claim. The notes
and references define botanical details that simple form/foliage tags cannot.
"""


def _plant(id, name, scientific, group, height, days, light, wildlife, color,
           form, foliage, petals, bloom_radius, flower_count, notes, references,
           category=None):
    return dict(id=id, name=name, scientific=scientific,
                category=category or ("Shrubs" if group == "Flowering bushes" else "Flowers"),
                group=group, height=height, days=days, light=light,
                wildlife=wildlife, color=color, form=form, foliage=foliage,
                petals=petals, bloom_radius=bloom_radius,
                flower_count=flower_count, notes=notes, references=references)


FLOWER_ADDITIONS = [
    _plant(148, "Cattleya orchid", "Cattleya labiata", "Orchids", .50, 14, "any", "bees", "c477ca",
           "orchid_cattleya", "strap", 6, .075, 4,
           "Clumped spindle-shaped pseudobulbs with one broad leathery leaf each. Three narrow sepals frame two broad wavy petals and a forward tubular lip with a magenta ruffled edge and yellow throat. New vegetative growth precedes the sheath, buds, then large open blooms.",
           ["https://www.aos.org/explore/cattleya", "https://longwoodgardens.org/blog/2022-09-21/orchids-emblems-national-pride"]),
    _plant(149, "Slipper orchid", "Paphiopedilum insigne", "Orchids", .30, 14, "shade", "bees", "c5a452",
           "orchid_slipper", "strap", 6, .050, 2,
           "Basal fans of plain green narrow leaves, with no pseudobulbs. Solitary flowers on upright stalks: tall white-edged dorsal sepal with maroon spots, two sideways petals, golden-brown inflated pouch, fused lower sepals behind it. A closed bud elongates before the pouch opens.",
           ["https://www.rhs.org.uk/plants/paphiopedilum/growing-guide", "https://www.rhs.org.uk/plants/pdfs/agm-lists/agm-orchids.pdf", "https://longwoodgardens.org/blog/2022-03-16/orchids-international-floral-emblem"]),
    _plant(150, "Dancing-lady orchid", "Oncidium sphacelatum", "Orchids", 1.00, 14, "any", "bees", "edc632",
           "orchid_oncidium", "strap", 6, .016, 32,
           "Flattened oval pseudobulbs carry long arching strap leaves. Slender branching sprays of small yellow flowers with brown markings; the broad lobed yellow lip forms a skirt below much smaller sepals and petals. New pseudobulbs and leaves form before branching flower stalks.",
           ["https://plants.ces.ncsu.edu/plants/oncidium-sphacelatum/"]),
    _plant(151, "Pansy orchid", "Miltoniopsis vexillaria", "Orchids", .45, 14, "shade", "bees", "dd90b8",
           "orchid_pansy", "strap", 6, .045, 7,
           "Compact flattened pseudobulbs with pale green strap foliage. Broad, almost flat pink flowers on gently arching lateral stalks; the large rounded white-marked lip has a yellow basal patch. Keep lip distinct from the two side petals. Emerging growth, arching bud stalk, then open flower faces.",
           ["https://www.aos.org/explore/miltoniopsis", "https://www.orchids.org/grexes/miltoniopsis-vexillaria"]),
    _plant(152, "Blue Vanda orchid", "Vanda coerulea", "Orchids", 1.20, 14, "any", "bees", "839acf",
           "orchid_vanda", "strap", 6, .050, 9,
           "One upright monopodial stem with alternating ranks of stout strap leaves and hanging silvery aerial roots. Side racemes bear broad waxy blue flowers with darker tessellated veins; petals twist at their bases and the small lip projects below the central column. Stem and roots develop before buds.",
           ["https://www.rhs.org.uk/plants/409682/vanda-coerulea/details", "https://www.kew.org/read-and-watch/vanda-ful-vandas"]),
    _plant(153, "Zygopetalum orchid", "Zygopetalum maculatum", "Orchids", .60, 14, "any", "bees", "a99b53",
           "orchid_zygo", "strap", 6, .030, 8,
           "Rounded pseudobulbs support glossy pleated lance-shaped leaves. Upright flower spikes carry green sepals and petals blotched brown, plus a broad white lip veined violet. Do not make the lip green. New growth becomes a leafy fan, then forms a spike with sequentially opening buds.",
           ["https://plants.ces.ncsu.edu/plants/zygopetalum/", "https://www.si.edu/object/zygopetalum-maculatum%3Aofeo-sg_2013-0564B", "https://powo.science.kew.org/taxon/urn%3Alsid%3Aipni.org%3Anames%3A661743-1/general-information"]),
    _plant(154, "Spider orchid", "Brassia verrucosa", "Orchids", .60, 14, "any", "bees", "bec37e",
           "orchid_spider", "strap", 6, .060, 9,
           "Oval pseudobulbs with two arching leaves. Arching racemes carry green-yellow flowers with very long narrow sepals and petals, small dark basal marks, and a shorter broad pale spotted lip. The long segments form a spider outline, not a six-pointed symmetrical star. Buds lengthen before unfolding.",
           ["https://www.aos.org/explore/brassia"]),
    _plant(155, "Australian rock orchid", "Dendrobium speciosum", "Orchids", .75, 14, "any", "bees", "f3e5b0",
           "orchid_rock", "strap", 6, .018, 48,
           "Thick ribbed canes topped by several leathery oblong leaves. Dense curved racemes carry many small cream flowers with yellowish outer parts and a small purple-spotted white lip. Mature canes persist as new shoots appear; crown flower spikes precede the dense flowering sprays.",
           ["https://www.anbg.gov.au/gnp/interns-2003/thelychiton-speciosum.html"]),
    _plant(156, "Bee orchid", "Ophrys apifera", "Orchids", .35, 14, "sun", "bees", "ca8cbb",
           "orchid_bee", "rosette", 6, .017, 5,
           "A terrestrial orchid with a low lance-leaf rosette and sparse upright flowering stem. Three pink sepals surround tiny green petals and a rounded velvety brown bee-like lip with yellow markings. Small basal growth precedes the bracted spike. UK populations commonly self-pollinate; the game wildlife tag is an abstraction.",
           ["https://www.wildlifetrusts.org/wildlife-explorer/wildflowers/bee-orchid"]),
    _plant(157, "Early purple orchid", "Orchis mascula", "Orchids", .40, 14, "any", "bees", "a448b5",
           "orchid_spike", "rosette", 6, .012, 30,
           "Basal rosette of broad lance leaves with purple spots. Upright dense spike of small purple flowers with an arched hood, broad three-lobed spotted lip and rear spur. Leaves establish before the elongated spike; lower flowers open before upper buds, unlike the existing large glasshouse orchids.",
           ["https://www.rhs.org.uk/plants/11905/orchis-mascula/details"]),
    _plant(158, "Cornflower", "Centaurea cyanus", "Wildflowers", .75, 8, "sun", "butterflies", "416cbd",
           "cornflower", "alternate", 12, .020, 9,
           "Thin branching stems with narrow grey-green leaves. Flower heads have enlarged fringed blue outer florets around a compact purple-blue disc, above overlapping scaly bracts. Juvenile growth is a narrow leafy tuft; enclosed bracted heads open into fringed heads, then become straw-coloured seed heads.",
           ["https://plants.ces.ncsu.edu/plants/centaurea-cyanus/"]),
    _plant(159, "Corncockle", "Agrostemma githago", "Wildflowers", .90, 8, "sun", "butterflies", "c65ba4",
           "star", "opposite", 5, .025, 6,
           "Slender hairy stems with opposite narrow leaves. Five broad pink-purple petals with fine dark lines; long pointed green sepals extend visibly between and beyond petals. A leafy seedling becomes a branched plant, pointed buds, then solitary flowers and enlarged seed capsules.",
           ["https://plants.ces.ncsu.edu/plants/agrostemma-githago/"]),
    _plant(160, "Red campion", "Silene dioica", "Wildflowers", .70, 9, "any", "bees", "d34b85",
           "notched", "opposite", 5, .014, 14,
           "Hairy stems and opposite oval leaves. Pink flowers have five deeply notched petals and a prominent ribbed tubular calyx. Start with a basal leafy clump, then branching stems and enclosed calyces; mature flower faces remain distinctly split into paired petal tips.",
           ["https://www.rhs.org.uk/plants/17328/silene-dioica/details"]),
    _plant(161, "Ragged robin", "Silene flos-cuculi", "Wildflowers", .60, 9, "sun", "butterflies", "d981ac",
           "ragged", "opposite", 5, .020, 12,
           "Loose branched stems above a basal rosette with narrow upper opposite leaves. Each of five pink petals is divided into four slender ragged lobes. Preserve gaps between strips. Early rosette develops a tall stem, elongated calyx buds, then airy pink flowers; grows in damp meadow ground, not underwater.",
           ["https://www.wildlifetrusts.org/wildlife-explorer/wildflowers/ragged-robin"]),
    _plant(162, "Meadow cranesbill", "Geranium pratense", "Wildflowers", .75, 11, "sun", "bees", "7d81ca",
           "star", "lobed", 5, .023, 12,
           "Palmately divided leaves and branched stems carry open violet-blue five-petalled flowers with fine darker veins. Young leaves unfold into the divided mound before buds rise above it; spent flowers form pointed beak-like seed structures. Rounded petal faces distinguish it from the existing daisy-type heads.",
           ["https://www.wildlifetrusts.org/wildlife-explorer/wildflowers/meadow-cranes-bill"]),
    _plant(163, "Field scabious", "Knautia arvensis", "Wildflowers", .80, 10, "sun", "butterflies", "b095cb",
           "pincushion", "lobed", 4, .025, 9,
           "Basal oblong leaves become deeply divided upper leaves on slender branching hairy stems. Lilac pincushion heads have many small florets, enlarged outer lobes and protruding stamens. A leafy rosette precedes round buds, flattened domed blooms, then rounded seed heads. Radius describes one composite head.",
           ["https://collections.rhs.org.uk/view/93005/knautia-arvensis", "https://doi.org/10.1111/1365-2745.13938"]),
    _plant(164, "Yarrow", "Achillea millefolium", "Wildflowers", .65, 10, "sun", "butterflies", "f0e9d3",
           "umbel", "fern", 5, .045, 7,
           "Finely divided feathery leaves along stems. Numerous tiny white composite heads form broad flat-topped corymbs; do not represent a whole corymb as one daisy. A low feathery tuft grows upright, produces clustered buds, then flat flower tables. Radius is the reduced model's whole corymb unit.",
           ["https://plants.ces.ncsu.edu/plants/achillea-millefolium/"]),
    _plant(165, "Purple coneflower", "Echinacea purpurea", "Wildflowers", 1.00, 12, "sun", "butterflies", "c87aaa",
           "coneflower", "alternate", 16, .055, 7,
           "Upright coarse hairy stems, broad lance leaves, drooping pink-purple ray florets and a prominent copper-orange spiny central cone. Leaf clump develops upright stems, green conical buds, then reflexing rays around the enlarging cone. Retain dark spiny seed cones in the late phase.",
           ["https://www.rhs.org.uk/plants/72079/rudbeckia-echinacea-purpurea/details", "https://plants.ces.ncsu.edu/plants/echinacea-purpurea/"]),
    _plant(166, "Black-eyed Susan", "Rudbeckia hirta", "Wildflowers", .80, 9, "sun", "butterflies", "ebba32",
           "coneflower", "alternate", 13, .045, 8,
           "Hairy upright stems with simple rough lance leaves. Golden yellow rays surround a raised dark brown dome; cone is shorter and rays flatter than Echinacea. Low leaf growth precedes branched stems and green head buds, then yellow flowering heads and dark seed heads.",
           ["https://plants.ces.ncsu.edu/plants/rudbeckia-hirta/"]),
    _plant(167, "Blanket flower", "Gaillardia aristata", "Wildflowers", .60, 9, "sun", "butterflies", "c7543b",
           "blanket", "alternate", 13, .040, 9,
           "A basal leafy clump carries branched stems and red-centred daisy heads whose rays have golden tips and three-toothed ends. Raised centres are burgundy-brown. Leaves and stems develop before spherical head buds; rays unfold into a two-tone disc, followed by rounded seed heads.",
           ["https://plants.ces.ncsu.edu/plants/gaillardia-aristata/"]),
    _plant(168, "Flannel flower", "Actinotus helianthi", "Wildflowers", .60, 11, "sun", "bees", "eeeadd",
           "flannel", "lobed", 10, .035, 8,
           "Grey-green velvety deeply lobed foliage on softly branching stems. The apparent white petals are long woolly bracts with green tips surrounding a pale yellow-green central umbel of tiny flowers. Small lobed growth precedes fuzzy buds and outward-spreading star-like bracts.",
           ["https://test.anbg.gov.au/gnp/interns-2002/actinotus-helianthi.html"]),
    _plant(169, "Strawflower", "Xerochrysum bracteatum", "Wildflowers", .75, 8, "sun", "butterflies", "dfa047",
           "strawflower", "alternate", 32, .025, 10,
           "Upright branching stems with lance leaves. Papery overlapping gold-orange bracts surround a yellow disc of true florets; inner bracts stay cupped while outer ones spread. Leafy juvenile stems produce round enclosed heads, then stiff layered blooms. Heads retain a dry papery appearance as they age.",
           ["https://www.anbg.gov.au/gallery/xerochrysum-bracteatum-adam-forster.html", "https://australianbg.gardenexplorer.org/taxon-8075.aspx"]),
    _plant(170, "Australian blue pincushion", "Brunonia australis", "Wildflowers", .30, 9, "sun", "butterflies", "798bc8",
           "pincushion", "rosette", 5, .020, 6,
           "Low soft obovate leaf rosette with almost leafless slender scapes. Each scape bears a rounded hemispherical blue head made of many tiny flowers with projecting pale styles. Young rosettes precede small rounded buds and lifted blue heads. Radius is a whole composite head.",
           ["https://plantselector.botanicgardens.sa.gov.au/Plants/Details/37", "https://www.anbg.gov.au/images/photo_cd/brunoniaceae/"]),
    _plant(171, "Chocolate lily", "Arthropodium strictum", "Wildflowers", .70, 10, "any", "bees", "a882bb",
           "lily_star", "strap", 6, .012, 14,
           "Basal narrow strap leaves and an airy branched raceme. Small mauve six-tepalled flowers have central anthers with conspicuous golden hairs; the flower face spreads from a short tube. Strap shoots precede a tall branching stalk, pointed buds and scattered open flowers. Tuberous roots remain below soil.",
           ["https://plantnet.rbgsyd.nsw.gov.au/cgi-bin/NSWfl.pl?lvl=sp&name=Arthropodium~strictum&page=nswfl", "https://spapps.environment.sa.gov.au/SeedsOfSA/speciesinformation.html?rid=475"]),
    _plant(172, "Fringed lily", "Thysanotus tuberosus", "Wildflowers", .50, 10, "sun", "bees", "b574bc",
           "fringed_lily", "strap", 6, .014, 10,
           "Fine grass-like basal leaves below wiry branched stalks. Three broad purple inner tepals have finely fringed margins; three outer tepals are narrower and unfringed, with central yellow anthers. Young grass-like shoots precede pointed buds; retain the contrast between fringed and plain segments when flowers open.",
           ["https://www.anbg.gov.au/apu/plants/thystube.html", "https://www.anbg.gov.au/stamps/stamp-thysan-tuberosus-05.html"]),
    _plant(173, "Daffodil", "Narcissus pseudonarcissus", "Cottage flowers", .40, 7, "any", "bees", "ead04d",
           "daffodil", "strap", 6, .035, 5,
           "Flat blue-green strap leaves and leafless stalks. One slightly nodding flower per stalk, with six pale-yellow tepals and a deeper yellow trumpet as long as the tepals. Bulb shoots emerge before sheathed buds; the trumpet extends and opens. Foliage persists after bloom before yellowing.",
           ["https://plants.ces.ncsu.edu/plants/narcissus-pseudonarcissus/"]),
    _plant(174, "Snowdrop", "Galanthus nivalis", "Cottage flowers", .18, 6, "shade", "bees", "f4f2e8",
           "snowdrop", "strap", 6, .010, 6,
           "Two narrow blue-green leaves per bulb and a slender arching stalk carrying one pendent flower. Three long white outer tepals surround three short inner tepals with green tip marks. Pointed leaf shoots precede a hooked bud and bell; preserve the different lengths of the two tepal whorls.",
           ["https://plants.ces.ncsu.edu/plants/galanthus-nivalis/"]),
    _plant(175, "Crocus", "Crocus vernus 'Remembrance'", "Cottage flowers", .10, 6, "sun", "bees", "9274bd",
           "cup", "strap", 6, .020, 7,
           "Very low violet goblets with six overlapping tepals, orange-yellow central stamens and narrow grass-like leaves with a white central stripe. Corm shoots rise with folded flower buds; cups open wider in sunlight and close in poor light. Short flowers stay close to the ground, not on leafy tall stems.",
           ["https://www.rhs.org.uk/plants/92662/crocus-vernus-remembrance/details", "https://plants.ces.ncsu.edu/plants/crocus/"]),
    _plant(176, "Hyacinth", "Hyacinthus orientalis", "Cottage flowers", .30, 7, "any", "bees", "a989cb",
           "hyacinth", "strap", 6, .011, 36,
           "Thick upright basal strap leaves surround a stout leafless stalk bearing a dense cylindrical raceme. Small waxy lavender flowers have tubular bases and six recurved lobes. Bulb leaves and a compact bud cluster emerge together; stalk elongates before lower bells open then upper ones.",
           ["https://plants.ces.ncsu.edu/plants/hyacinthus-orientalis/"]),
    _plant(177, "English bluebell", "Hyacinthoides non-scripta", "Cottage flowers", .40, 8, "shade", "bees", "6a72b7",
           "bluebell", "strap", 6, .010, 20,
           "Basal strap foliage and a curved scape with blue-violet pendent narrow bells concentrated on one side. Six fused tepals curl back at the tips; cream anthers. Leaf shoots precede the drooping bud stalk; bell rows open while the stalk remains curved, distinguishing native bluebells from stiff Spanish bluebells.",
           ["https://www.rhs.org.uk/plants/8890/hyacinthoides-non-scripta/details", "https://www.kew.org/plants/bluebell"]),
    _plant(178, "Giant ornamental allium", "Allium giganteum", "Cottage flowers", 1.50, 11, "sun", "bees", "a577c3",
           "globes", "strap", 6, .090, 3,
           "Broad basal strap leaves and tall straight leafless scapes. One dense spherical umbel per scape, composed of many lilac six-tepalled star flowers on radiating pedicels. Broad leaves precede stalk elongation; papery bud sheath splits to reveal the expanding sphere. Radius describes a whole umbel.",
           ["https://plants.ces.ncsu.edu/plants/allium-giganteum/"]),
    _plant(179, "Lily of the valley", "Convallaria majalis", "Cottage flowers", .25, 8, "shade", "bees", "f0eee5",
           "lily_valley", "strap", 6, .006, 18,
           "Two broad smooth elliptical leaves clasp the base of each shoot. A separate arching raceme carries tiny round white pendent bells with six short recurved teeth on one side. Rolled leaf shoots open before green bud rows become white bells. Include broad leaves rather than the narrow straps of bluebells.",
           ["https://plants.ces.ncsu.edu/plants/convallaria-majalis/"]),
    _plant(180, "Ranunculus", "Ranunculus asiaticus (double garden form)", "Cottage flowers", .40, 9, "sun", "bees", "e8a5a8",
           "rosette_bloom", "lobed", 36, .030, 6,
           "Basal divided leaves beneath slim branching flower stems. Double cultivated pink flowers have tightly layered rounded petals spiralling around the centre. Leaf rosette precedes stalks and round buds; outer petals unfold first while inner ones remain cupped. Extra petals describe the selected garden form, not the five-petalled wild species.",
           ["https://plants.ces.ncsu.edu/plants/ranunculus-asiaticus/"]),
    _plant(181, "Windflower", "Anemone coronaria", "Cottage flowers", .35, 8, "sun", "bees", "c05671",
           "anemone", "lobed", 8, .032, 6,
           "Deeply cut basal foliage, a small leaf whorl below each flower, and slim stalks carrying solitary red open cups. Coloured sepals surround a black centre and dark stamens. Leafy rosette develops stalks and oval buds, then broadly spread flowers; plant dies back after flowering.",
           ["https://plants.ces.ncsu.edu/plants/anemone-coronaria/"]),
    _plant(182, "Snapdragon", "Antirrhinum majus", "Cottage flowers", .80, 9, "sun", "bees", "d76a90",
           "snapdragon", "opposite", 5, .020, 20,
           "Upright stalks with narrow leaves, opposite lower and often alternate higher. Pink flowers form a raceme, each with a closed two-lipped mouth and swollen lower palate. Seedlings form leafy stems before tight terminal buds; lower dragon-mouth flowers open first beneath the remaining top buds.",
           ["https://plants.ces.ncsu.edu/plants/antirrhinum-majus/"]),
    _plant(183, "Sweet William", "Dianthus barbatus", "Cottage flowers", .45, 9, "sun", "butterflies", "bc4e73",
           "dianthus", "opposite", 5, .045, 5,
           "Opposite lance leaves below dense flat terminal clusters. Each five-petalled red-pink flower has toothed petal edges and a pale contrasting eye above a narrow tubular calyx. Juvenile leafy clump becomes short upright stems; clustered buds open into a flower table. Model individual small flowers rather than one enlarged disc.",
           ["https://plants.ces.ncsu.edu/plants/dianthus-barbatus/"]),
    _plant(184, "Stock", "Matthiola incana (single-flowered form)", "Cottage flowers", .60, 9, "sun", "bees", "c098c5",
           "stock", "alternate", 4, .013, 24,
           "Grey-green narrow hairy foliage along upright stems. Dense racemes of lavender four-petalled cross-shaped flowers, with upper buds and lower open blooms. Basal leaf growth develops a thick flowering stalk before sequential flowers; choose single stock for visible four-petal form and useful wildlife attraction.",
           ["https://plants.ces.ncsu.edu/plants/matthiola-incana/"]),
    _plant(185, "Love-in-a-mist", "Nigella damascena", "Cottage flowers", .45, 8, "sun", "bees", "92b0d0",
           "nigella", "fern", 5, .020, 9,
           "Finely thread-divided green foliage and lacy involucral bracts surrounding pale blue five-sepalled flowers. Tiny true petals sit near the centre beneath many stamens. Early feathery growth develops stems, then enclosed buds and open stars; aged flowers become inflated round capsules with conspicuous pointed styles.",
           ["https://plants.ces.ncsu.edu/plants/nigella-damascena/"]),
    _plant(186, "Calendula", "Calendula officinalis", "Cottage flowers", .45, 7, "sun", "bees", "de9134",
           "aster", "alternate", 22, .028, 10,
           "Branching soft stems carry oblong slightly hairy leaves. Orange composite heads have several rows of flat rays and an orange-brown disc, above green involucral bracts. Leafy juvenile growth precedes plump closed heads, then open flowers; curved hooked achenes develop in spent heads.",
           ["https://plants.ces.ncsu.edu/plants/calendula-officinalis/"]),
    _plant(187, "Zinnia", "Zinnia elegans (double garden form)", "Cottage flowers", .75, 8, "sun", "butterflies", "dc6687",
           "zinnia", "opposite", 30, .040, 9,
           "Stiff branching stems with opposite broad rough sessile leaves. Pink double composite heads have stacked rows of broad blunt rays and a small yellow-orange central disc, above overlapping bracts. Leaf pairs build upward, buds swell, then layered rays open. Selected garden form adds rows beyond a single wild-type head.",
           ["https://plants.ces.ncsu.edu/plants/zinnia-elegans/"]),
    _plant(188, "Columbine", "Aquilegia vulgaris", "Cottage flowers", .70, 11, "any", "bees", "8b75b1",
           "columbine", "compound", 10, .023, 9,
           "Compound foliage with rounded three-lobed leaflets. Nodding violet flowers have five outer sepals and five inner petals, each with a backward curled nectar spur. Rounded leaf tufts precede branched stems and hanging buds; opened bells retain the conspicuous five hooked spurs above their faces.",
           ["https://plants.ces.ncsu.edu/plants/aquilegia/", "https://www.rhs.org.uk/plants/aquilegia"]),
    _plant(189, "Bleeding heart", "Lamprocapnos spectabilis", "Cottage flowers", .80, 11, "shade", "butterflies", "d581a4",
           "heart", "compound", 4, .013, 20,
           "Divided blue-green foliage beneath arching stems with a one-sided hanging row of pink heart-shaped flowers. Two swollen outer petals surround two protruding white inner petals. Leafy shoots precede curved flower stems and small pendent buds; hearts swell and open, then foliage yellows after the flowering period.",
           ["https://plants.ces.ncsu.edu/plants/lamprocapnos-spectabilis/"]),
    _plant(190, "Hellebore", "Helleborus orientalis", "Cottage flowers", .45, 12, "shade", "bees", "ae829a",
           "hellebore", "compound", 5, .027, 7,
           "Leathery palmately divided serrated leaves on long stalks. Nodding dusty-pink cups have five broad sepals surrounding a ring of tubular nectaries and many cream stamens. Low leaf growth develops stout bud stems, then open cups; persistent sepals surround enlarging green follicles after true petals fade.",
           ["https://plants.ces.ncsu.edu/plants/helleborus-orientalis/"]),
    _plant(191, "Astilbe", "Astilbe chinensis", "Cottage flowers", .75, 11, "shade", "bees", "c990b5",
           "plume", "compound", 5, .080, 7,
           "Dense mound of divided serrated foliage beneath upright tapering branched pink plumes. Each plume contains many tiny flowers, not large petals. Foliage expands before the branched bud panicles lift above it; flowers open through the plume, then turn bronze-brown. Radius describes one compound plume's base.",
           ["https://www.rhs.org.uk/plants/astilbe/growing-guide"]),
    _plant(192, "Penstemon", "Penstemon digitalis", "Cottage flowers", .90, 11, "sun", "bees", "eee1e2",
           "tubular", "opposite", 5, .010, 22,
           "Basal lance leaves and opposite upper leaves on upright stems. Loose branched panicles carry white blush-tinged tubular flowers with two upper and three lower lobes, plus a hairy sterile stamen at the throat. Basal clump precedes stems, pendant pointed buds, and open two-lipped tubes.",
           ["https://plants.ces.ncsu.edu/plants/penstemon-digitalis/"]),
    _plant(193, "Tall garden phlox", "Phlox paniculata", "Cottage flowers", 1.00, 12, "sun", "butterflies", "c485b3",
           "phlox", "opposite", 5, .012, 36,
           "Opposite pointed leaves along stiff upright stalks. Rounded terminal panicles are built of many flat pink five-lobed flower faces, each attached to a long narrow corolla tube. Paired leafy stems develop terminal buds, then a domed floral cluster; retain visible spaces between several flowering stems.",
           ["https://plants.ces.ncsu.edu/plants/phlox-paniculata/"]),
    _plant(194, "Canterbury bells", "Campanula medium", "Cottage flowers", .85, 10, "any", "bees", "9786c1",
           "bell", "alternate", 5, .024, 16,
           "A basal rosette of long rough leaves develops a tall branching stalk carrying large inflated violet-blue bells. Each bell has a broad five-lobed rim and a green star-shaped calyx behind it. First leafy rosette, then leafy stalk and pointed buds, then bells along the upper stem.",
           ["https://plants.ces.ncsu.edu/plants/campanula-medium/"]),
    _plant(195, "Oriental lily", "Lilium 'Star Gazer' (Oriental hybrid)", "Cottage flowers", .90, 11, "sun", "butterflies", "d58ca3",
           "oriental_lily", "alternate", 6, .085, 5,
           "Strong upright stem clothed in narrow lance leaves. Large outward/upward-facing pink six-tepalled flowers have white edges, crimson speckles, curved tips and six projecting orange-brown anthers. Leafy bulb shoots elongate before large pointed buds; tepals open widely as stamens extend.",
           ["https://www.rhs.org.uk/plants/articles/graham-rice/perennials-and-bulbs/get-growing-lilies", "https://www.rhs.org.uk/plants/pdfs/plant-register-supplements/lilies/lily-register-and-checklist.pdf"]),
    _plant(196, "Sweet violet", "Viola odorata", "Cottage flowers", .15, 8, "shade", "bees", "9472b6",
           "violet", "heart", 5, .010, 9,
           "Low heart-shaped leaf rosettes spread by runners. Small fragrant violet flowers rise on separate thin pedicels, with two upper petals, two lateral petals and a broader lower spurred petal. Young rounded leaves become a low mat before tiny nodding buds and asymmetric flowers appear.",
           ["https://plants.ces.ncsu.edu/plants/viola-odorata/"]),
    _plant(197, "Lady's mantle", "Alchemilla mollis", "Cottage flowers", .45, 10, "any", "bees", "c4c768",
           "froth", "lobed", 4, .045, 9,
           "Soft rounded leaves with shallow scalloped lobes and radiating folds hold water droplets. Airy branched sprays carry tiny lime-yellow flowers with four sepals and no showy petals. Folded leaf shoots widen into a dense mound before fine flower stalks and frothy sprays; radius is the small spray unit.",
           ["https://plants.ces.ncsu.edu/plants/alchemilla-mollis/"]),
    _plant(198, "Tropical hibiscus", "Hibiscus rosa-sinensis", "Flowering bushes", 2.00, 18, "sun", "butterflies", "dd735f",
           "hibiscus", "woody", 5, .070, 10,
           "Woody upright branching shrub with alternate glossy toothed leaves. Large coral five-petalled funnels have a long central staminal column tipped by five stigmas. Small woody leaf shoots branch outward before pointed buds; opening flowers preserve the projecting column. Mature blooms are borne on new growth.",
           ["https://plants.ces.ncsu.edu/plants/hibiscus-rosa-sinensis/"]),
    _plant(199, "Daphne", "Daphne odora", "Flowering bushes", 1.40, 18, "any", "butterflies", "d7a9b9",
           "cluster", "woody", 4, .006, 36,
           "Compact evergreen framework with glossy alternate leaves crowded near branch tips. Tight terminal clusters of waxy four-lobed flowers, deep pink outside and pale pink-white within, on short tubes. Young shoots acquire dense leaf tips before plump terminal bud clusters open. Preserve leaves during the flowering phase.",
           ["https://plants.ces.ncsu.edu/plants/daphne-odora/"]),
    _plant(200, "Japanese pieris", "Pieris japonica", "Flowering bushes", 2.00, 20, "shade", "bees", "eee8dc",
           "pieris", "woody", 5, .004, 54,
           "Dense evergreen branches with narrow glossy leaves in crowded tip clusters and bronze-red new growth. Drooping branched chains of tiny white urn-shaped flowers. Young woody shoots have reddish tips; hanging bud clusters mature before the flowers open. Keep individual urns narrow, with a constricted five-toothed mouth.",
           ["https://plants.ces.ncsu.edu/plants/pieris-japonica/"]),
    _plant(201, "Snowball viburnum", "Viburnum opulus 'Roseum'", "Flowering bushes", 2.50, 20, "any", "bees", "eee9d7",
           "snowball", "woody", 5, .060, 14,
           "Broad deciduous shrub with opposite three-lobed leaves. Spherical terminal heads of sterile enlarged florets start lime-green, becoming white. Young shoots build the branch framework, then leaves unfold and rounded heads expand. This cultivar is sterile and offers little floral food; wildlife is a general gameplay attraction tag.",
           ["https://plants.ces.ncsu.edu/plants/viburnum-opulus-roseum/"]),
    _plant(202, "Mock orange", "Philadelphus coronarius", "Flowering bushes", 2.40, 20, "sun", "bees", "f2ead6",
           "mock_orange", "woody", 4, .020, 26,
           "Arching deciduous woody stems with opposite toothed oval leaves. Small groups of four broad white petals surround conspicuous yellow stamens. Young shoots grow into an open arching framework, then leaves and rounded buds; fragrant flowers appear in short lateral clusters rather than large hydrangea heads.",
           ["https://plants.ces.ncsu.edu/plants/philadelphus-coronarius/"]),
    _plant(203, "Weigela", "Weigela florida", "Flowering bushes", 2.00, 18, "sun", "bees", "d17f9b",
           "trumpet", "woody", 5, .013, 32,
           "Arching woody branches carry opposite pointed serrated leaves. Pink five-lobed trumpet flowers arise in small groups along side shoots, with paler throats. Young leafy shoots form the arching shrub; narrow tubular buds swell before mouths flare open. Maintain multiple trunk stems and outward branch tips.",
           ["https://plants.ces.ncsu.edu/plants/weigela-florida/"]),
    _plant(204, "Deutzia", "Deutzia gracilis", "Flowering bushes", 1.20, 16, "any", "bees", "f1ecdf",
           "cluster", "woody", 5, .009, 40,
           "Compact deciduous shrub with many slender arching stems and opposite narrow serrated leaves. White five-petalled star flowers form short upright racemes along branch tips. New shoots branch into a low mound, followed by leaf pairs and grouped buds; mature blossom shows many separate small stars.",
           ["https://plants.ces.ncsu.edu/plants/deutzia-gracilis/"]),
    _plant(205, "Forsythia", "Forsythia x intermedia", "Flowering bushes", 2.20, 18, "sun", "bees", "e8c34b",
           "forsythia", "woody", 4, .017, 36,
           "Long arching cane-like deciduous stems. Bright yellow flowers have four long narrow lobes around a short tube and open along bare wood before leaves. Young vegetative growth builds the framework, then flower buds expand; flowering model should have sparse small emerging opposite leaves, not a dense green canopy.",
           ["https://plants.ces.ncsu.edu/plants/forsythia-x-intermedia/"]),
    _plant(206, "Flowering quince", "Chaenomeles speciosa", "Flowering bushes", 2.20, 20, "sun", "bees", "cb6b6b",
           "quince", "woody", 5, .024, 27,
           "Tangled thorny upright woody canes with alternate glossy toothed leaves. Coral-red five-petalled cups with many yellow stamens bloom close to older wood before most leaves emerge. Small woody shoots develop a thorned framework, swelling round buds, then blossom with sparse emerging leaves; fruits later become small green-yellow pomes.",
           ["https://plants.ces.ncsu.edu/plants/chaenomeles-speciosa/"]),
    _plant(207, "Spirea", "Spiraea x vanhouttei", "Flowering bushes", 2.00, 18, "sun", "bees", "eee9df",
           "spirea", "woody", 5, .026, 20,
           "A fountain of arching deciduous branches with small alternate shallow-lobed leaves. Dense rounded corymbs of tiny white five-petalled flowers line older branches. Young shoots grow upward then bend outward; grouped buds become a cascading flower-covered outline. Radius is each compact corymb, with visible individual florets.",
           ["https://plants.ces.ncsu.edu/plants/spiraea-x-vanhouttei/"]),
    _plant(208, "Abelia", "Abelia x grandiflora", "Flowering bushes", 1.60, 17, "sun", "butterflies", "dfb6bd",
           "tubular", "woody", 5, .007, 34,
           "Fine arching red-brown twigs with small opposite glossy leaves. Pale pink-white tubular flowers have five short spreading lobes and sit among persistent reddish star-shaped sepals. Leafy shoots form an open rounded shrub; slim buds open at shoot tips. Keep rusty calyces after some flowers have fallen.",
           ["https://plants.ces.ncsu.edu/plants/abelia-x-grandiflora/"]),
    _plant(209, "Escallonia", "Escallonia rubra", "Flowering bushes", 2.00, 18, "sun", "bees", "c76a8e",
           "cluster", "woody", 5, .006, 40,
           "Dense evergreen branching shrub with small alternate glossy serrated leaves. Deep pink flowers form short terminal clusters, each with a narrow tube and five rounded spreading lobes. Young woody shoots gain dense foliage before tight buds and flower clusters; keep the canopy structured by visible individual leaves.",
           ["https://plants.ces.ncsu.edu/plants/escallonia-rubra/"]),
    _plant(210, "Hebe", "Veronica speciosa (syn. Hebe speciosa)", "Flowering bushes", 1.20, 16, "sun", "butterflies", "b178ab",
           "hebe", "woody", 4, .004, 48,
           "Compact evergreen shrub with broad glossy opposite leaves in crossing pairs. Short dense magenta-purple flower racemes project from upper leaf axils; tiny four-lobed flowers have long pale stamens. Paired leaf shoots form a rounded framework, then tight spikes elongate and flower. Spikes remain separate from the leaves.",
           ["https://www.rhs.org.uk/plants/105261/hebe-speciosa/details"]),
    _plant(211, "Ceanothus", "Ceanothus thyrsiflorus", "Flowering bushes", 2.20, 19, "sun", "bees", "688abf",
           "ceanothus", "woody", 5, .025, 22,
           "Evergreen woody framework with small alternate glossy oval leaves showing three basal veins. Numerous dense blue clusters consist of tiny flowers with projecting stamens. Leafy branch growth becomes a rounded shrub before fine clustered buds open into blue clouds. Radius is one compound cluster, not an individual flower.",
           ["https://plants.ces.ncsu.edu/plants/ceanothus-thyrsiflorus/"]),
    _plant(212, "Hardy fuchsia", "Fuchsia magellanica", "Flowering bushes", 1.60, 17, "any", "bees", "c96d95",
           "fuchsia", "woody", 4, .018, 26,
           "Arching slender woody branches with opposite or whorled serrated leaves. Hanging flowers have a long red tube, four reflexed red sepals, a shorter purple petal skirt and projecting stamens. Young leafy shoots arch outward; elongated pendent buds open into two contrasting tiers, followed later by small dark berries.",
           ["https://plants.ces.ncsu.edu/plants/fuchsia-magellanica/"]),
    _plant(213, "Mexican orange blossom", "Choisya ternata", "Flowering bushes", 1.80, 18, "any", "bees", "f0ead9",
           "choisya", "woody", 5, .012, 28,
           "Dense evergreen shrub with opposite compound leaves, each divided into three glossy oblong leaflets. White five-petalled star flowers with yellow stamens form terminal clusters. Small trifoliate shoots develop a rounded canopy, then compact pale buds and star clusters. Keep the leaflets separate; this is not a single-leaf orange tree.",
           ["https://plants.ces.ncsu.edu/plants/choisya-ternata/"]),
    _plant(214, "Correa", "Correa reflexa", "Flowering bushes", 1.20, 16, "any", "native birds", "be7b70",
           "correa", "woody", 4, .008, 22,
           "Small woody shrub with opposite oval softly hairy leaves. Pendent long tubular red flowers have contrasting green-yellow four-lobed tips and projecting stamens. Young twigs carry paired leaves before hanging bud tubes elongate and tips open. Select the common red-and-green flower form; native honeyeaters use the nectar.",
           ["https://anbg.gov.au/gnp/gnp7/correa-reflexa.html"], "Natives"),
    _plant(215, "Pink boronia", "Boronia pinnata", "Flowering bushes", 1.50, 17, "any", "bees", "d594b8",
           "boronia", "woody", 4, .006, 36,
           "Slender arching shrub with opposite pinnate leaves divided into narrow leaflets. Waxy pale pink-mauve flowers have four oval petals and eight central stamens; they form open little stars rather than Correa-like tubes. Young compound-leaved shoots branch before tiny buds and numerous small flowers develop.",
           ["https://www.anbg.gov.au/gnp/gnp4/boronia-pinnata.html"], "Natives"),
    _plant(216, "Flowering tea-tree", "Leptospermum scoparium", "Flowering bushes", 2.00, 18, "sun", "bees", "e0afb8",
           "tea_tree", "woody", 5, .010, 42,
           "Fine twiggy upright shrub with small alternate sharp-pointed leaves. Pale pink five-petalled flowers sit close along twigs, with a dark central disc and a ring of short stamens. Small leafy shoots build fine branches, then round buds and separate open flowers. Woody seed capsules can persist after bloom.",
           ["https://www.anbg.gov.au/leptospermum/leptospermum-scoparium.html"], "Natives"),
    _plant(217, "Spotted emu bush", "Eremophila maculata", "Flowering bushes", 1.50, 17, "sun", "native birds", "bd715d",
           "emu_bush", "woody", 5, .010, 25,
           "Dense twiggy shrub with small alternate lanceolate leaves. Red-orange tubular flowers have a spotted pale interior, curved swollen tube, two upper lobes and three lower lobes; stamens project from the mouth. Young leaves and branches precede curved buds and open tubes. Dry pointed fruits follow flowers.",
           ["https://anpsa.org.au/plant_profiles/eremophila-maculata/", "https://anbg.gov.au/photo/apii/id/a/30785"], "Natives"),
]

assert len(FLOWER_ADDITIONS) == 70
assert [plant["id"] for plant in FLOWER_ADDITIONS] == list(range(148, 218))
